packages:
  - apps/*
  - packages/*
  - tools/*

catalogMode: prefer

catalogs:
  vue:
    '@pinia/colada': ^1.4.2
    '@vueuse/core': ^14.4.0
    '@vueuse/router': ^14.4.0
    pinia: ^4.0.3
    reka-ui: ^2.10.3
    vue: ^3.5.41
    vue-i18n: ^11.4.8
    vue-router: ^5.2.0
  build:
    '@unocss/reset': ^66.8.0
    '@vitejs/plugin-legacy': ^8.2.3
    '@vitejs/plugin-vue': ^6.0.8
    terser: ^5.50.0
    unocss: ^66.8.0
    vite: npm:@voidzero-dev/vite-plus-core@latest
    vite-plugin-vue-devtools: ^8.2.1
    vitest: 4.1.9
  tooling:
    '@oxlint/plugins': 1.73.0
    '@types/node': ^26.2.0
    taze: ^21.1.0
    typescript: ^7.0.2
    vite-plus: latest
overrides:
  vite: 'catalog:build'
  vitest: 'catalog:build'
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: '*'
    vitest: '*'
allowBuilds:
  core-js: true
  vue-demi: true
