packages:
  - apps/*
  - packages/*
  - tools/*

catalogMode: prefer

catalog:
  '@types/node': ^26.1.1
  taze: ^19.14.1
  typescript: ^6.0.3
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vitest: 4.1.9
  vite-plus: latest
  vue: ^3.5.39
  '@vueuse/core': ^14.3.0
  '@vueuse/router': ^14.3.0
  '@vitejs/plugin-vue': ^6.0.7
  unocss: ^66.7.5
  '@unocss/reset': ^66.7.5
  vconsole: ^3.15.1
  '@vitejs/plugin-legacy': ^8.1.0
  terser: ^5.48.0
  vue-i18n: ^11.4.6
  core-js: ^3.49.0
overrides:
  vite: 'catalog:'
  vitest: 'catalog:'
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: '*'
    vitest: '*'
allowBuilds:
  core-js: true
